exclude: '^src/validate_pyproject/_vendor'

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-xml
  - id: check-yaml
  - id: check-toml
  - id: check-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: requirements-txt-fixer
  - id: mixed-line-ending
    args: ['--fix=auto']  # replace 'auto' with 'lf' to enforce Linux/Mac line endings or 'crlf' for Windows

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.8.3
  hooks:
      # Run the linter
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
